---
baseURL: https://sakibsadmanshajib.com
languageCode: en-us
title: Sakib Sadman Shajib
pygmentsstyle: monokai
disqusShortname: sakibsadmanshajib
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
